/*
 * Copyright 2011 by Dominic Clifton <me@dominicclifton.name>
 *
 * This file is part of FreeWPC.
 *
 * FreeWPC is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * FreeWPC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FreeWPC; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <freewpc.h>
#include <combo_definitions.h>

/*
 * TODO Ideally this file should be autogenerated via genmachine.
 *
 * The combo definitions reference game-specific callset_*() methods and switch defines
 *
 */

/****************************************************************************
 *
 * Combo steps
 *
 ****************************************************************************/

const combo_step_t cstp_left_outer_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP,  TIME_2S }
	}
};

const combo_step_t cstp_left_outer_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_RIGHT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,    TIME_3S },
		{ SW_MIDDLE_ROLLOVER,  TIME_3S },
		{ SW_RIGHT_ROLLOVER,   TIME_3S }
	}
};

const combo_step_t cstp_right_outer_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_RIGHT_OUTER_LOOP, TIME_2S }
	}
};

const combo_step_t cstp_right_outer_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,   TIME_3S },
		{ SW_MIDDLE_ROLLOVER, TIME_3S },
		{ SW_RIGHT_ROLLOVER,  TIME_3S }
	}
};

const combo_step_t cstp_inner_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_INNER_LOOP_ENTRY,  TIME_2S }
	}
};

const combo_step_t cstp_inner_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,   TIME_3S },
		{ SW_MIDDLE_ROLLOVER, TIME_3S },
		{ SW_RIGHT_ROLLOVER,  TIME_3S }
	}
};

const combo_step_t cstp_skid_pad_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_SKID_PAD_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_skid_pad_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_SKID_PAD_EXIT,  0 } // no time limit for switch, sometimes the ball gets stuck just before the switch
	}
};

const combo_step_t cstp_route_66_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ROUTE_66_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_route_66_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ROUTE_66_EXIT,  0 } // no time limit for switch, sometimes the ball gets stuck just before the switch
	}
};

const combo_step_t cstp_zr1_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ZR1_BOTTOM_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_zr1_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ZR1_TOP_ENTRY,  TIME_500MS }
	}
};

const combo_step_t cstp_wildcard_5sec = {
	.flags = CSTP_WILDCARD,
	.switches = 0,
	.time_allowed = TIME_5S
};


/****************************************************************************
 *
 * Combo definitions
 *
 ****************************************************************************/

/*
 * single shot combos
 */

extern void callset_left_orbit_combo_shot(void);
const combo_def_t left_orbit_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LO")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_left_orbit_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_right_orbit_combo_shot(void);
const combo_def_t right_orbit_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_right_orbit_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit
	}
};


extern void callset_route66_ramp_combo_shot(void);
const combo_def_t route66_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_route66_ramp_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit
	}
};

extern void callset_zr1_ramp_combo_shot(void);
const combo_def_t zr1_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_zr1_ramp_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit
	}
};

extern void callset_skidpad_ramp_combo_shot(void);
const combo_def_t skidpad_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("SP")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_skidpad_ramp_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

extern void callset_inner_loop_combo_shot(void);
const combo_def_t inner_loop_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("IL")
	.flags = DEFAULT_COMBO_FLAGS | CF_USE_FOR_SHOT_CHAINING,
	.fn = callset_inner_loop_combo_shot,
	.steps = 2,
	.step_list = {
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit
	}
};
/*
 * two-shot combos
 */

extern void callset_lr_rl_combo_shot(void);
const combo_def_t lr_rl_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LO RO")
	.fn = callset_lr_rl_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit
	}
};

extern void callset_rl_lr_combo_shot(void);
const combo_def_t rl_lr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO LO")
	.fn = callset_rl_lr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_rl_rl_combo_shot(void);
const combo_def_t rl_rl_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO RO")
	.fn = callset_rl_rl_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit
	}
};

extern void callset_lr_lr_combo_shot(void);
const combo_def_t lr_lr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LO LO")
	.fn = callset_lr_lr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_ll_rr_combo_shot(void);
const combo_def_t ll_rr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LL RR")
	.fn = callset_ll_rr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_entry,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_entry
	}
};

extern void callset_rr_ll_combo_shot(void);
const combo_def_t rr_ll_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RR LL")
	.fn = callset_rr_ll_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_entry,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_entry
	}
};

extern void callset_rl_il_combo_shot(void);
const combo_def_t rl_il_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO IL")
	.fn = callset_rl_il_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit
	}
};

extern void callset_inner_loop_to_skidpad_ramp_combo_shot(void);
const combo_def_t il_skidpad_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("IL SP")
	.fn = callset_inner_loop_to_skidpad_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

extern void callset_rl_skidpad_combo_shot(void);
const combo_def_t rl_skidpad_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO SP")
	.fn = callset_rl_skidpad_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};


extern void callset_route66_ramp_to_zr1_ramp_combo_shot(void);
const combo_def_t route66_ramp_to_zr1_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66 ZR1")
	.fn = callset_route66_ramp_to_zr1_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit
	}
};

extern void callset_zr1_ramp_to_route66_ramp_combo_shot(void);
const combo_def_t zr1_ramp_to_route66_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1 R66")
	.fn = callset_zr1_ramp_to_route66_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_route_66_entry,
		&cstp_route_66_exit
	}
};

extern void callset_inner_loop_to_inner_loop_combo_shot(void);
const combo_def_t il_il_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("IL IL")
	.fn = callset_inner_loop_to_inner_loop_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit
	}
};

extern void callset_zr1_ramp_to_skidpad_ramp_combo_shot(void);
const combo_def_t zr1_ramp_to_skidpad_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1 SP")
	.fn = callset_zr1_ramp_to_skidpad_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

extern void callset_route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo_shot(void);
const combo_def_t route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66 ZR1 SP")
	.fn = callset_route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo_shot,
	.steps = 8,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

extern void callset_zr1_ramp_to_inner_loop_combo_shot(void);
const combo_def_t zr1_ramp_to_inner_loop_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1 IL")
	.fn = callset_zr1_ramp_to_inner_loop_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit
	}
};

extern void callset_skidpad_ramp_to_zr1_ramp_combo_shot(void);
const combo_def_t skidpad_ramp_to_zr1_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("SP ZR1")
	.fn = callset_skidpad_ramp_to_zr1_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit
	}
};

extern void callset_left_orbit_to_zr1_ramp_combo_shot(void);
const combo_def_t left_orbit_to_zr1_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LO ZR1")
	.fn = callset_left_orbit_to_zr1_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit
	}
};

extern void callset_right_orbit_to_route66_ramp_combo_shot(void);
const combo_def_t right_orbit_to_route66_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RO R66")
	.fn = callset_right_orbit_to_route66_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_route_66_entry,
		&cstp_route_66_exit
	}
};

extern void callset_skidpad_ramp_to_left_orbit_combo_shot(void);
const combo_def_t skidpad_ramp_to_left_orbit_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("SP LO")
	.fn = callset_skidpad_ramp_to_left_orbit_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_route66_ramp_to_left_orbit_combo_shot(void);
const combo_def_t route66_ramp_to_left_orbit_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66 LO")
	.fn = callset_route66_ramp_to_left_orbit_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

/****************************************************************************
 *
 * Combo configuration
 *
 ****************************************************************************/

const combo_def_t *machine_combos[COMBO_COUNT] = {
	&left_orbit_combo,
	&right_orbit_combo,
	&zr1_ramp_combo,
	&route66_ramp_combo,
	&skidpad_ramp_combo,
	&inner_loop_combo,
	&lr_rl_combo,
	&rl_lr_combo,
	&rl_rl_combo,
	&lr_lr_combo,
	&ll_rr_combo,
	&rr_ll_combo,
	&rl_il_combo,
	&rl_skidpad_combo,
	&route66_ramp_to_zr1_ramp_combo,
	&zr1_ramp_to_route66_ramp_combo,
	&zr1_ramp_to_skidpad_ramp_combo,
	&route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo,
	&il_il_combo,
	&il_skidpad_combo,
	&zr1_ramp_to_inner_loop_combo,
	&skidpad_ramp_to_zr1_ramp_combo,
	&left_orbit_to_zr1_ramp_combo,
	&right_orbit_to_route66_ramp_combo,
	&skidpad_ramp_to_left_orbit_combo,
	&route66_ramp_to_left_orbit_combo
};
