/*
 * Copyright 2011 by Dominic Clifton <me@dominicclifton.name>
 *
 * This file is part of FreeWPC.
 *
 * FreeWPC is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * FreeWPC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FreeWPC; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <freewpc.h>

/*
 * TODO Ideally this file should be autogenerated via genmachine.
 *
 * The combo definitions reference game-specific callset_*() methods and switch defines
 *
 * There MUST be a call to combo_reset_current_step_markers() after machine_combos_count has been set via an 'init' callset handler.
 */

#ifdef CONFIG_COMBOS

const combo_step_t cstp_wildcard_5sec = {
	.flags = CSTP_WILDCARD,
	.switches = 0,
	.time_allowed = TIME_5S
};


const combo_def_t dummy_combo = {
	COMBO_NAME("DUMMY")
	.fn = null_function,
	.steps = 5,
	.step_list = {
		&cstp_wildcard_5sec,
	}
};



#define COMBO_COUNT 1

const combo_def_t *machine_combos[COMBO_COUNT] = {
	&dummy_combo,
};

U8 current_step_markers[COMBO_COUNT]; // 1-based index
U16 step_time_list[COMBO_COUNT]; // the system timer at the time the last-match step that counted
U16 step_time_allowed_list[COMBO_COUNT]; // the time that was allowed by the last-hit switch or step that counted
U16 wildcard_time_list[COMBO_COUNT]; // the system timer at the time the last wildcard step that counted

CALLSET_ENTRY(machine_combos, init, start_ball) {
	machine_combos_count = COMBO_COUNT;
	combo_reset_current_step_markers();
}
#else
//FIXME genmachine expects these to be defined because it doesn't know about #ifdef CONFIG_COMBOS
__far__(C_STRING(MACHINE_PAGE)) void machine_combos_init(void) {}
#endif
