/*
 * Copyright 2011 by Dominic Clifton <me@dominicclifton.name>
 *
 * This file is part of FreeWPC.
 *
 * FreeWPC is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * FreeWPC is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FreeWPC; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <freewpc.h>
#include <combo_definitions.h>

/*
 * TODO Ideally this file should be autogenerated via genmachine.
 *
 * The combo definitions reference game-specific callset_*() methods and switch defines
 *
 * There MUST be a call to combo_reset_current_step_markers() after machine_combos_count has been set via an 'init' callset handler.
 *
 * TODO Every 1 second check the current combo markers and light appropriate lamps
 */

#ifdef CONFIG_COMBOS

const combo_step_t cstp_left_outer_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP,  TIME_2S }
	}
};

const combo_step_t cstp_left_outer_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_RIGHT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,    TIME_3S },
		{ SW_MIDDLE_ROLLOVER,  TIME_3S },
		{ SW_RIGHT_ROLLOVER,   TIME_3S }
	}
};

const combo_step_t cstp_right_outer_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_RIGHT_OUTER_LOOP, TIME_2S }
	}
};

const combo_step_t cstp_right_outer_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,   TIME_3S },
		{ SW_MIDDLE_ROLLOVER, TIME_3S },
		{ SW_RIGHT_ROLLOVER,  TIME_3S }
	}
};

const combo_step_t cstp_wildcard_5sec = {
	.flags = CSTP_WILDCARD,
	.switches = 0,
	.time_allowed = TIME_5S
};

extern void callset_lr_rl_combo_shot(void);
const combo_def_t lr_rl_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LR RL")
	.fn = callset_lr_rl_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit
	}
};

extern void callset_rl_lr_combo_shot(void);
const combo_def_t rl_lr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RL LR")
	.fn = callset_rl_lr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_rl_rl_combo_shot(void);
const combo_def_t rl_rl_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RL RL")
	.fn = callset_rl_rl_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit
	}
};

extern void callset_lr_lr_combo_shot(void);
const combo_def_t lr_lr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LR LR")
	.fn = callset_lr_lr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_exit
	}
};

extern void callset_ll_rr_combo_shot(void);
const combo_def_t ll_rr_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("LL RR")
	.fn = callset_ll_rr_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_entry,
		&cstp_wildcard_5sec,
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_entry
	}
};

extern void callset_rr_ll_combo_shot(void);
const combo_def_t rr_ll_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RR LL")
	.fn = callset_rr_ll_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_entry,
		&cstp_wildcard_5sec,
		&cstp_left_outer_loop_entry,
		&cstp_left_outer_loop_entry
	}
};

const combo_step_t cstp_inner_loop_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_INNER_LOOP_ENTRY,  TIME_2S }
	}
};

const combo_step_t cstp_inner_loop_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 4,
	.switch_list = {
		{ SW_LEFT_OUTER_LOOP, TIME_1S },
		{ SW_LEFT_ROLLOVER,   TIME_3S },
		{ SW_MIDDLE_ROLLOVER, TIME_3S },
		{ SW_RIGHT_ROLLOVER,  TIME_3S }
	}
};

extern void callset_rl_il_combo_shot(void);
const combo_def_t rl_il_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RL IL")
	.fn = callset_rl_il_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_inner_loop_entry,
		&cstp_inner_loop_exit
	}
};

const combo_step_t cstp_skid_pad_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_SKID_PAD_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_skid_pad_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_SKID_PAD_EXIT,  0 } // no time limit for switch, sometimes the ball gets stuck just before the switch
	}
};

const combo_step_t cstp_route_66_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ROUTE_66_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_route_66_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ROUTE_66_EXIT,  0 } // no time limit for switch, sometimes the ball gets stuck just before the switch
	}
};

const combo_step_t cstp_zr1_entry = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ZR1_BOTTOM_ENTRY,  TIME_1S }
	}
};

const combo_step_t cstp_zr1_exit = {
	.flags = CSTP_NO_FLAGS,
	.switches = 1,
	.switch_list = {
		{ SW_ZR1_TOP_ENTRY,  TIME_500MS }
	}
};

extern void callset_rl_skidpad_combo_shot(void);
const combo_def_t rl_skidpad_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("RL SP")
	.fn = callset_rl_skidpad_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_right_outer_loop_entry,
		&cstp_right_outer_loop_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};


extern void callset_route66_ramp_to_zr1_ramp_combo_shot(void);
const combo_def_t route66_ramp_to_zr1_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66 ZR1")
	.fn = callset_route66_ramp_to_zr1_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit
	}
};

extern void callset_zr1_ramp_to_route66_ramp_combo_shot(void);
const combo_def_t zr1_ramp_to_route66_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1 R66")
	.fn = callset_zr1_ramp_to_route66_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_route_66_entry,
		&cstp_route_66_exit
	}
};

extern void callset_zr1_ramp_to_skidpad_ramp_combo_shot(void);
const combo_def_t zr1_ramp_to_skidpad_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("ZR1 SP")
	.fn = callset_zr1_ramp_to_skidpad_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

extern void callset_route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo_shot(void);
const combo_def_t route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo = {
	DEFAULT_COMBO,
	COMBO_NAME("R66 ZR1 SP")
	.fn = callset_route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo_shot,
	.steps = 5,
	.step_list = {
		&cstp_route_66_entry,
		&cstp_route_66_exit,
		&cstp_wildcard_5sec,
		&cstp_zr1_entry,
		&cstp_zr1_exit,
		&cstp_wildcard_5sec,
		&cstp_skid_pad_entry,
		&cstp_skid_pad_exit
	}
};

const combo_def_t *machine_combos[COMBO_COUNT] = {
	&lr_rl_combo,
	&rl_lr_combo,
	&rl_rl_combo,
	&lr_lr_combo,
	&ll_rr_combo,
	&rr_ll_combo,
	&rl_il_combo,
	&rl_skidpad_combo,
	&route66_ramp_to_zr1_ramp_combo,
	&zr1_ramp_to_route66_ramp_combo,
	&zr1_ramp_to_skidpad_ramp_combo,
	&route66_ramp_to_zr1_ramp_to_skidpad_ramp_combo
};

U8 current_step_markers[COMBO_COUNT]; // 1-based index
U16 step_time_list[COMBO_COUNT]; // the system timer at the time the last-match step that counted
U16 step_time_allowed_list[COMBO_COUNT]; // the time that was allowed by the last-hit switch or step that counted
U16 wildcard_time_list[COMBO_COUNT]; // the system timer at the time the last wildcard step that counted
U16 wildcard_time_allowed_list[COMBO_COUNT]; // the allowed time for the last wildcard steo that counted

CALLSET_ENTRY(machine_combos, init, start_ball) {
	machine_combos_count = COMBO_COUNT;
	combo_reset_current_step_markers();
}
#else
//FIXME genmachine expects these to be defined because it doesn't know about #ifdef CONFIG_COMBOS
__far__(C_STRING(MACHINE_PAGE)) void machine_combos_init(void) {}
#endif
