#!/bin/bash
# generates C source code using imagemagick
# example usage: "tools/genfont2 supercar 9 "-crop 0x0-2-1" > supercar9.fon"
# other useful values for args are:
# "+trim" - only useful for fonts where every single character is the same HEIGHT
# see "man convert" for more possible arguments
 
font="$1"
pointsize="$2"
args="$3"
#charlist=`echo . , \- \! \? \[ \] \% \< \> \( \) \# A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 `
charlist=`echo . $ , \- \! \? \[ \] \% \( \) \# A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 0 1 2 3 4 5 6 7 8 9 `

echo "#include <freewpc.h>"

for char in ${charlist}; do
	charstripped="${char//\./period}"
	charstripped="${charstripped//\$/dollar}"
	charstripped="${charstripped/,/comma}"
	charstripped="${charstripped/-/minus}"
	charstripped="${charstripped//\!/bang}"
	charstripped="${charstripped//\?/question}"
	charstripped="${charstripped//\[/lbrace}"
	charstripped="${charstripped//\]/rbrace}"
	charstripped="${charstripped//\%/percent}"
	charstripped="${charstripped//\</lessthan}"
	charstripped="${charstripped//\>/morethan}"
	charstripped="${charstripped//\(/lpar}"
	charstripped="${charstripped//\)/rpar}"
	charstripped="${charstripped//\#/hash}"
	
	prefix="glyph_${font}${pointsize}_${charstripped}"
	convert -pointsize ${pointsize} -font ${font}.ttf ${args} label:$char xbm:- | sed -e "s/-/${prefix}/" | sed -e "s/{/{ ${prefix}_width, ${prefix}_height,/"
done

echo "static char *${font}${pointsize}_glyphs[] = {"
for char in ${charlist}; do
	charstripped="${char//\./period}"
	charstripped="${charstripped//\$/dollar}"
	charstripped="${charstripped/,/comma}"
	charstripped="${charstripped/-/minus}"
	charstripped="${charstripped//\!/bang}"
	charstripped="${charstripped//\?/question}"
	charstripped="${charstripped//\[/lbrace}"
	charstripped="${charstripped//\]/rbrace}"
	charstripped="${charstripped//\%/percent}"
	charstripped="${charstripped//\</lessthan}"
	charstripped="${charstripped//\>/morethan}"
	charstripped="${charstripped//\(/lpar}"
	charstripped="${charstripped//\)/rpar}"
	charstripped="${charstripped//\#/hash}"
	
	prefix="glyph_${font}${pointsize}_${charstripped}"
	echo "	['${char}'] = ${prefix}_bits,"
done
echo "};"

echo "const font_t font_${font}${pointsize} = {"
echo "	.height = ${pointsize},"
echo "	.glyphs = ${font}_glyphs,"
echo "};"
